import os

APP_NAME = "Creative Spark Agency CRM"
WINDOW_MIN_WIDTH = 1280
WINDOW_MIN_HEIGHT = 760
SIDEBAR_WIDTH = 270
API_BASE_URL = os.getenv("AD_AGENCY_API_URL", "http://127.0.0.1:8000")
API_TIMEOUT_SECONDS = float(os.getenv("AD_AGENCY_API_TIMEOUT", "5"))
APPLICATION_POLL_INTERVAL_MS = int(
    os.getenv("AD_AGENCY_APPLICATION_POLL_MS", "10000")
)
